name: "auto assign reviewers"
on:
  - pull_request

jobs:
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm i -g @zeit/ncc
    - run: yarn package
    - uses: ./
      with:
        config: '.github/assign-by-files.yml'
        token: ${{ secrets.GITHUB_TOKEN }}
